import Head from 'next/head'
import type { AppProps } from 'next/app'
import { appWithTranslation } from 'next-i18next'
import { ClientOnly } from '@/lib/clientOnly'
import { useEffect } from 'react'
import { setConsole } from '@/lib/utils'
import { initFetchData } from '@/lib/native'
import '@/styles/globals.css'

function App({ Component, pageProps }: AppProps) {
  useEffect(() => {
    initFetchData()
    setConsole()
  }, [])

  return <>
    <Head>
      <title>Create Next App</title>
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no,viewport-fit=cover"
      />
      <meta name="description" content="Generated by create next app" />
    </Head>
    <ClientOnly>
      <Component {...pageProps} />
    </ClientOnly>
  </>
}

export default appWithTranslation(App)